# - hosts: all_groups
#   become: yes
#   roles:
#   - { role: common }

- hosts: admin
  become: yes
  vars_files:
    - "vars/main.yml"
  roles:
  - { role: admin }

# - hosts: cluster
#   become: yes
#   roles:
#   - { role: cluster }