---
# tasks file for role/common

- name: "install_task | Update repositories cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install_task | Update all packages to their latest version"
  apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"

- name: "install_task | packages"
  apt: name={{item}} state=present
  with_items:
    - wget
    - python3

- name: "install_task | Executar comando bash"
  command: /bin/bash -c 'hostnamectl set-hostname $(hostname -s).ramos.com'

