---
# tasks file for role/admin

- name: "install_task | packages"
  apt: name={{item}} state=present
  with_items:
    - docker.io

- name: "install_task | Verificar se o grupo docker existe"
  group:
    name: docker
    state: present

- name: "install_task | Adicionar o usuário ao grupo docker"
  user:
    name: vagrant
    groups: docker
    append: yes